In [1]:
import tensorflow as tf
import numpy as np 

#### Create two constants

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
c = tf.constant(5.0)
total = tf.multiply(c,tf.add(a,b))
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("Mul:0", shape=(), dtype=float32)


### Create session with tf.Session()

In [3]:
sess = tf.Session()

#### Run our operation with opened session

In [4]:
sess.run(total)

35.0

In [5]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.90694034 0.42674637 0.71411645]
[0.50385547 0.36713517 0.05490315]
(array([1.632291 , 1.3744874, 1.0099632], dtype=float32), array([2.6322908, 2.3744874, 2.009963 ], dtype=float32))


### Dont forget to close the session and reset the graph

In [6]:
sess.close()
tf.reset_default_graph()

In [7]:
try:
    sess.run(vec)
except:
    print("error")

error


### Another example 

In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.add(x,y)

#### Try to use with block for oppening session

In [9]:
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: 3, y: 4.5}))
    print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

try:    
    sess.run(z,feed_dict={x: 3, y: 4.5})
except:
    print("Error")

7.5
[3. 7.]
Error
