In [4]:
import tensorflow as tf
import numpy as np 

#### Create two constants

In [5]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
c = tf.constant(5.0)
total = tf.multiply(c,tf.add(a,b))
print(a)
print(b)
print(c)
print(total)

Tensor("Const_3:0", shape=(), dtype=float32)
Tensor("Const_4:0", shape=(), dtype=float32)
Tensor("Const_5:0", shape=(), dtype=float32)
Tensor("Mul_1:0", shape=(), dtype=float32)


### Create session with tf.Session()

In [6]:
sess = tf.Session()

#### Run our operation with opened session

In [7]:
sess.run(total)

35.0

In [8]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(out1))
print(ses)
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.4094907  0.6668551  0.09315443]
[1.5844854 1.3846873 1.649407 ]
[0.6852735  0.8012438  0.29206455]
(array([1.8631614, 1.049994 , 1.2236601], dtype=float32), array([2.8631616, 2.049994 , 2.22366  ], dtype=float32))


### Dont forget to close the session and reset the graph

In [9]:
sess.close()
tf.reset_default_graph()

In [10]:
try:
    sess.run(vec)
except:
    print("error")

error


### Another example 

In [15]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.add(x,y)

#### Try to use with block for oppening session

In [18]:
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: 3, y: 4.5}))
    print(sess.run(z, feed_dict={x: [[1, 3],[1, 3]], y: [[2, 4],[1, 3]]}))

 sess.run(z,feed_dict={x: 3, y: 4.5})


7.5
[[3. 7.]
 [2. 6.]]


RuntimeError: Attempted to use a closed Session.